services:
  # 后台应用
  tailchat-admin:
    image: caifu-chat:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: docker-compose.env
    depends_on:
      - mongo
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.priority=100"
      - "traefik.http.services.admin.loadbalancer.server.port=3000"
    networks:
      - internal
    command: pnpm start:admin

networks:
  internal:
    name: tailchat-internal
