#!/usr/bin/env node
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var yargs_1 = __importDefault(require("yargs/yargs"));
var helpers_1 = require("yargs/helpers");
var create_plugin_1 = require("./create-plugin");
var bundle_1 = require("../bundler/bundle");
var utils_1 = require("../bundler/utils");
var ora_1 = __importDefault(require("ora"));
var utils_2 = require("./utils");
(0, yargs_1.default)((0, helpers_1.hideBin)(process.argv))
    .command('createPlugin', 'Create a new Plugin', function (yargs) {
    yargs;
    // .option('name', {
    //   describe: 'Plugin Name',
    // })
}, function () {
    (0, create_plugin_1.createPluginTemplate)();
})
    .command('buildPlugin <pluginName>', 'Bundle Plugin', function () { }, function (argv) { return __awaiter(void 0, void 0, void 0, function () {
    function bundleSinglePlugin(name) {
        return __awaiter(this, void 0, void 0, function () {
            var pluginPackageJsonPath, spinner, startTime, usage, err_1;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        pluginPackageJsonPath = (0, utils_2.getPluginPackagePath)(name);
                        spinner = (0, ora_1.default)("Building plugin [".concat(name, "]...")).start();
                        startTime = new Date().valueOf();
                        _a.label = 1;
                    case 1:
                        _a.trys.push([1, 3, , 4]);
                        return [4 /*yield*/, (0, bundle_1.buildPlugin)(pluginPackageJsonPath)];
                    case 2:
                        _a.sent();
                        usage = new Date().valueOf() - startTime;
                        spinner.succeed("Bundle [".concat(name, "] success in ").concat(usage, "ms!"));
                        return [3 /*break*/, 4];
                    case 3:
                        err_1 = _a.sent();
                        spinner.fail("Bundle [".concat(name, "] error"));
                        console.error(err_1);
                        return [3 /*break*/, 4];
                    case 4: return [2 /*return*/];
                }
            });
        });
    }
    var pluginName, allPluginDirs, _i, _a, name_1;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                pluginName = argv['pluginName'];
                if (!(pluginName === 'all')) return [3 /*break*/, 5];
                allPluginDirs = (0, utils_1.getPluginDirs)();
                if (allPluginDirs.length === 0) {
                    console.warn('Not found and plugin in:', (0, utils_1.getPluginDirContainerPath)());
                }
                _i = 0, _a = (0, utils_1.getPluginDirs)();
                _b.label = 1;
            case 1:
                if (!(_i < _a.length)) return [3 /*break*/, 4];
                name_1 = _a[_i];
                return [4 /*yield*/, bundleSinglePlugin(name_1)];
            case 2:
                _b.sent();
                _b.label = 3;
            case 3:
                _i++;
                return [3 /*break*/, 1];
            case 4: return [3 /*break*/, 7];
            case 5: return [4 /*yield*/, bundleSinglePlugin(pluginName)];
            case 6:
                _b.sent();
                _b.label = 7;
            case 7: return [2 /*return*/];
        }
    });
}); })
    .command('watchPlugin <pluginName>', 'Build and watch Plugin', function () { }, function (argv) { return __awaiter(void 0, void 0, void 0, function () {
    function watchSinglePlugin(name) {
        return __awaiter(this, void 0, void 0, function () {
            var pluginPackageJsonPath, watcher, spinner;
            return __generator(this, function (_a) {
                pluginPackageJsonPath = (0, utils_2.getPluginPackagePath)(name);
                watcher = (0, bundle_1.watchPlugin)(pluginPackageJsonPath);
                spinner = (0, ora_1.default)({
                    prefixText: function () { return "[".concat((0, utils_2.getShortTimeStr)(), "]: [").concat(name, "] "); },
                });
                watcher.on('event', function (event) {
                    if (event.code === 'BUNDLE_START') {
                        spinner.start("Building ".concat(event.output.join(',')));
                    }
                    else if (event.code === 'BUNDLE_END') {
                        spinner.succeed("Building Successful in ".concat(event.duration, "ms"));
                    }
                    else if (event.code === 'ERROR') {
                        spinner.fail("Build Error: ".concat(event.error.message));
                    }
                });
                return [2 /*return*/];
            });
        });
    }
    var pluginName, _i, _a, name_2;
    return __generator(this, function (_b) {
        switch (_b.label) {
            case 0:
                pluginName = argv['pluginName'];
                if (!(pluginName === 'all')) return [3 /*break*/, 5];
                _i = 0, _a = (0, utils_1.getPluginDirs)();
                _b.label = 1;
            case 1:
                if (!(_i < _a.length)) return [3 /*break*/, 4];
                name_2 = _a[_i];
                return [4 /*yield*/, watchSinglePlugin(name_2)];
            case 2:
                _b.sent();
                _b.label = 3;
            case 3:
                _i++;
                return [3 /*break*/, 1];
            case 4: return [3 /*break*/, 7];
            case 5: return [4 /*yield*/, watchSinglePlugin(pluginName)];
            case 6:
                _b.sent();
                _b.label = 7;
            case 7: return [2 /*return*/];
        }
    });
}); })
    .demandCommand(1).argv;
